# Generated by Django 2.0.6 on 2018-06-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='news.Category', verbose_name='Kategorie'),
        ),
    ]
