# Generated by Django 2.0.6 on 2018-06-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180618_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pic',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='Obrazek'),
        ),
        migrations.AddField(
            model_name='news',
            name='pic_caption',
            field=models.CharField(default='Podpis obrazka', max_length=255),
        ),
    ]
